# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    groups:
      wordpress:
        patterns:
          - '@wordpress/*'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      actions-major:
        patterns:
          - '*'
        update-types:
          - 'major'
    cooldown:
      default-days: 7
