version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      wordpress:
        patterns:
          - '@wordpress/*'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
