import ServerSideRender from '@wordpress/server-side-render';

import metadata from './block.json';

export function Edit() {
	// ServerSideRender allows us to reuse the markup generated by `render.php`
	// instead of duplicating the rendering logic in JavaScript.
	return <ServerSideRender block={ metadata.name } />;
}
