name: Build Live Branch

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'bin/**'
      - '**/tests/**'
      - '**/*.md'
      - '.github/**'
      - '!.github/workflows/pr-build-live-branch.yml'

concurrency:
  # Cancel concurrent jobs on pull_request but not push, by including the run_id in the concurrency group for the latter.
  group: build-${{ github.event_name == 'push' && github.run_id || 'pr' }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  build:
    if: github.repository_owner == 'Automattic' && github.event.pull_request.draft == false && github.event.pull_request.user.login != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: '8.2'

      - name: Setup Node.js
        uses: Automattic/vip-actions/nodejs-setup@trunk
        with:
          node-version-file: .nvmrc
          ignore-scripts: true

      - name: Prepare plugin zip
        run: |
          cd "$GITHUB_WORKSPACE" || exit
          npm run plugin-zip

      - name: Upload plugin zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-data-blocks-pr${{ github.event.pull_request.number }}-${{ github.sha }}
          path: remote-data-blocks.zip
          retention-days: 7
          if-no-files-found: 'error'
          overwrite: true

      - name: Save PR metadata
        run: |
          echo "${{ github.event.pull_request.number }}" > pr_number.txt
          echo "${{ github.sha }}" > commit_sha.txt

      - name: Upload PR metadata
        uses: actions/upload-artifact@v4
        with:
          name: pr-metadata
          path: |
            pr_number.txt
            commit_sha.txt
          retention-days: 1
