name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag version matches plugin version
        run: |
          TAG_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          PLUGIN_VERSION=$(grep -oP "Version: \K[^\s]+(?=\s*$)" remote-data-blocks.php)
          if [ "$TAG_VERSION" != "$PLUGIN_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match plugin version ($PLUGIN_VERSION)"
            exit 1
          fi
          echo "Version match confirmed: $TAG_VERSION"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Build plugin zip
        run: npm install && npm run plugin-zip

      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          files: remote-data-blocks.zip
          generate_release_notes: true
