name: Release
on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version has increased
        id: check_version
        run: |
          # Get the version from the file
          FILE_VERSION=$(grep -oP "(?<=Version: ).*" remote-data-blocks.php)
          echo "File version: $FILE_VERSION"
          echo "file_version=$FILE_VERSION" >> $GITHUB_OUTPUT

          # Get the latest released tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "Latest released tag: $LATEST_TAG"

          # Compare versions
          if [ "$(printf '%s\n' "$LATEST_TAG" "$FILE_VERSION" | sort -V | tail -n1)" = "$FILE_VERSION" ] && [ "$LATEST_TAG" != "$FILE_VERSION" ]; then
            echo "Version in file is newer than the latest released tag"
            echo "version_increased=true" >> $GITHUB_OUTPUT
          else
            echo "Version in file is not newer than the latest released tag"
            echo "version_increased=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup PHP
        if: steps.check_version.outputs.version_increased == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Build plugin zip
        if: steps.check_version.outputs.version_increased == 'true'
        run: npm install && npm run plugin-zip

      - name: 'Release'
        if: steps.check_version.outputs.version_increased == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check_version.outputs.file_version }}
          files: remote-data-blocks.zip
          generate_release_notes: true
