name: Build latest zip file
on:
  workflow_run:
    workflows: [Test]
    branches: [trunk]
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set the TAG environment variable
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Build plugin zip
        run: npm install && npm run plugin-zip

      - name: 'Release plugin zip'
        uses: ncipollo/release-action@v1
        with:
          artifacts: remote-data-blocks.zip
          commit: ${{ github.sha }}
          tag: ${{ env.TAG }}
          makeLatest: true
