name: Release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'add/tag-releasing'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Build plugin zip
        run: npm install && npm run plugin-zip

      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          files: remote-data-blocks.zip
          generate_release_notes: true
