name: Test
on:
  pull_request:
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        if: ${{ matrix.php-version != '8.3' }}
        run: composer test

      - name: Run tests and generate coverage
        if: ${{ matrix.php-version == '8.3' }}
        run: composer test-coverage

      - name: Upload coverage to Codecov
        if: ${{ matrix.php-version == '8.3' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/phpunit/clover.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: Automattic/vip-actions/nodejs-setup@a430b095ce5adc30beace82eade2653abd5deedf
        with:
          node-version-file: .nvmrc

      - name: Run tests
        run: npm run test:js:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/vitest/clover.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
